dist: xenial

matrix:
  include:
    - language: node_js # node version specified in .nvmrc

      # install dependencies from package-lock.json
      install:
        - npm ci

      # define environment variables
      env:
        # FONTAWESOME_NPM_AUTH_TOKEN
        - secure: 'w5qtMjO6L6Ym30wxPNh66B+3FXma2nR/1cZgEQ3edbLjw+nnqCTtFz/7wGyhe2Sj2BOWFrSxmkP53Z5KShjTLTBwoyPtJICLywI8y1Q+TFu2liKoOWaDQ5aVqi8sICdL+trPJpAi5x/jKLh1E/z7l2TiuDC1F99zl4Kr1WAUcOK3h9vwJnin8w/0/prhaG0i5FJcteITc4Ee3od4wNF3+S8fSGT0qdLKPIaOPPvbcQuXgn6dlSSMSRsbOSwwzbWc28KMmmEng2tcSm5VYqw5dKCvo58WcyqKwkPK8uCZUYr97vSd1Tj2qAzVhbAPG7KkaxRz8CgaTFAD4SCFBMw4DGj96m/ep821a5Jtn5glq4d4ug7PfKDiUTmtasxOae3BM8Ar3TidRYWSMyKPf2ZcP3wryx/UpXCBxFis2+H9S4cBK2/dng1/nilDBD4WtzNNwHOXrt6UI6x4oUG3a2Ylb85P8S2uQDE3Nl9lEfhA4n6NcKniNLwon7TbuPYHFYmkoZzQMgqKVCize6KhJwH4vTL7LW+VFpQk7JOUXzOQrPGd+vNiVKzT2BFX/1y0r122zIXI8j8omtGkBuJ5sVY/aOoI2xxyVLaTrFjvo6eQj3XTuRRpHcLyx2kzhARIqpoLRAwiUd+f8dVqJddOz45h1YvTkFwAHmBzTSvY2vYgtIQ='

      # run security audit (only for pull requests), linter, and unit tests
      script:
        - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npx audit-ci --config ./audit-ci.json; fi
        - npm run lint
        - sudo env "PATH=$PATH" npm run test
