dist: xenial

matrix:
  include:
    - language: node_js         # node version specified in .nvmrc

      # install dependencies
      install:
        - npm install
     
      # define environment variables 
      env:
        - EXAMPLE_TEST=testExample!

      # run linter and unit tests
      script:
        - npm run lint
        - sudo env "PATH=$PATH" npm run test
