require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'BraveAlertApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  target 'BraveAlertAppTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'BraveAlertApp-tvOS' do
  # Pods for BraveAlertApp-tvOS

  target 'BraveAlertApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# Prevent building for Apple Silicon (~arm64) in simulator mode
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings.delete "VALID_ARCHS"
    config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET' # Suppress warnings resulting
  end
end
