export const ALERT_STATUS = {
  NEW: 'NEW',
  REMINDING: 'REMINDING',
  RESPONDING: 'RESPONDING',
  REPORTING: 'REPORTING',
  DONE: 'DONE',
}

export const ALERT_TYPE = {
  BUTTONS_NOT_URGENT: 'BUTTONS_NOT_URGENT',
  BUTTONS_URGENT: 'BUTTONS_URGENT',
  SENSOR_STILLNESS: 'SENSOR_STILLNESS',
  SENSOR_DURATION: 'SENSOR_DURATION',
  SENSOR_UNKNOWN: 'SENSOR_UNKNOWN',
}

export const NOTIFICATION_STATUS = {
  NEW: 'NEW',
  READ: 'READ',
  CONFIRMED: 'CONFIRMED',
}
